#!/usr/bin/env python3.4

import os
import sys

_APP_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, _APP_PATH)

os.environ['FSS_DEBUG_LOG'] = '1'

import fss.constants
import fss.config.log
import fss.orchestrator

#path = os.path.expanduser('~/Documents')
path = os.path.expanduser('/Volumes/tower/images')

filter_rules = [
#    (fss.constants.FT_FILE, fss.constants.FILTER_INCLUDE, '*.MP4'),

    (fss.constants.FT_DIR, fss.constants.FILTER_INCLUDE, 'main'),
    (fss.constants.FT_DIR, fss.constants.FILTER_INCLUDE, '2014'),
#    (fss.constants.FT_DIR, fss.constants.FILTER_INCLUDE, '*234*'),
    (fss.constants.FT_DIR, fss.constants.FILTER_INCLUDE, '*123*'),
]

fq_handler_class_name = 'package.module.Class'

o = fss.orchestrator.Orchestrator(path, filter_rules, fq_handler_class_name)
o.run()
