#!/usr/bin/env python3.4

import os
import sys

_APP_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, _APP_PATH)

import fss.config.log
import fss.orchestrator

#path = os.path.expanduser('~/Documents')
path = os.path.expanduser('/Volumes/tower/images')

filter_rules = [
]

fq_handler_class_name = 'package.module.Class'

o = fss.orchestrator.Orchestrator(path, filter_rules, fq_handler_class_name)
o.run()
