import fss.constants

WORKER_IDLE_SLEEP_S = 1
QUIT_CHECK_TICK_INTERVAL = 10
QUIT_CHECK_INTERVAL_S = 1

PROGRESS_LOG_TICK_INTERVAL = 1000

GENERATOR_MAX_OUTPUT_QUEUE_SIZE = 5000
FILTER_MAX_OUTPUT_QUEUE_SIZE = 5000

SHUTDOWN_LOG_DEPLETE_CHECK_INTERVAL_S = 1

COMPONENTS = [
    fss.constants.PC_GENERATOR,
    fss.constants.PC_FILTER,
    fss.constants.PC_EXECUTOR,
]
